fileLocation: # 파일 업로드 경로
  image: 본인경로/arterium/src/main/resources/static/img/temp/

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html   # 파일 확장자
    # TODO : 배포시 true 처리
    cache: false # default true 개발 시에는 false 로 두는게 좋다.
    enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/arterium;MODE=MYSQL
    # url: jdbc:h2:~/testDB;MODE=MYSQL  #local test DB 저장
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2: # 테스트를 위해 테스트 DB 사용
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 100MB
      location: ${fileLocation.image}

  # 로깅 설정...
  logging:
    level:
      me.arterium: DEBUG

          # SignatureAlgorithm.HS512 알고리즘을 사용
jwt:
  header: Authorization
  secret: ArTeriumSecRetkEyArteriUmsecREtkeY #base64 인코딩
  token-validity-in-seconds: 86400

server:
  port: 8080
